### ISSUE TITLE
local storage

### ISSUE THREAD

**Issue by barkyq** [tmaegel/ntodotxt#37] opened 2024-03-25 16:20 UTC
Hello,

I am using `v0.6.1` installed from fdroid

I cannot seem to get the local storage to work; I select a local folder (e.g. a new folder `/storage/emulated/0/ntodo.txt/`) and then the screen goes completely gray and the app seemingly crashes.

So far I can only get the app to work with the default path `/data/user/0/de.tnmgl.ntodotxt/cache`; however, this default path seems quite hard to access (even through `adb`) which makes it hard/impossible to backup my todolist.

It would be also be nice to have some sort of "export" feature in the app, so I can save my `todo.txt` even if it is stored in the default local storage `/data/user/0/de.tnmgl.ntodotxt/cache`

**Comment by tmaegel** [comment] 2024-03-25 17:45
Please use the latest version (v0.7.0) and look If the issue ist still exists. This issue was fixed with Version v0.6.2.

An export function ist already on my roadmap.

**Comment by barkyq** [comment] 2024-03-25 19:59
Thanks! Fixed when updated to 0.7.0 on F-Droid.

**Closed** 2024-03-25 20:14 UTC
